name: Publish Drama to central.sonartype.com

on:
  release:
    types: [ created ]

jobs:
  build:
    name: Build and publish drama

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: build

      - name: Publish to GitHub Packages
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: publish --no-parallel --info
        env:
          SIGNING_KEYID: ${{ secrets.SIGNING_KEYID }}
          SINGING_SECRETKEYRINGFILE: ${{ secrets.SINGING_SECRETKEYRINGFILE }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SONAR_USERNAME: ${{ secrets.SONAR_USERNAME }}
          SONAR_PASSWORD: ${{ secrets.SONAR_PASSWORD }}