name: Publish Drama to central.sonartype.com

on:
  release:
    types: [ created ]

jobs:
  build:
    name: Build and publish drama

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin

      - name: Prepare GPG key
        run: |
          echo '${{secrets.SINGING_SECRETKEYRINGFILE}}' | base64 -d > publish_key.gpg
          gpg --quiet --batch --yes --decrypt --passphrase="${{secrets.SIGNING_PASSWORD}}" \
          --output secret.gpg publish_key.gpg

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-disabled: true

      - name: Execute Gradle build
        run: ./gradlew build
        env:
          SONAR_USERNAME: ${{ secrets.SONAR_USERNAME }}
          SONAR_PASSWORD: ${{ secrets.SONAR_PASSWORD }}

      - name: Publish to sonartype
        run: ./gradlew publish --no-parallel --info --rerun-tasks
        env:
          SIGNING_KEYID: ${{ secrets.SIGNING_KEYID }}
          SINGING_SECRETKEYRINGFILE: secret.gpg
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SONAR_USERNAME: ${{ secrets.SONAR_USERNAME }}
          SONAR_PASSWORD: ${{ secrets.SONAR_PASSWORD }}